// Real golf club catalog with manufacturer loft specs
// Sources: manufacturer websites, Golf Digest, MyGolfSpy equipment databases

export interface ClubModel {
  brand: string;
  model: string;
  year: number;
  category: "Players" | "Players Distance" | "Game Improvement" | "Super Game Improvement" | "Wedge Set" | "Hybrid/Fairway";
  clubs: { name: string; loft: number }[];
}

export const CLUB_CATALOG: ClubModel[] = [

  // ===========================
  // TITLEIST
  // ===========================
  {
    brand: "Titleist",
    model: "T100 (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 21 },
      { name: "4 Iron", loft: 24 },
      { name: "5 Iron", loft: 27 },
      { name: "6 Iron", loft: 30 },
      { name: "7 Iron", loft: 34 },
      { name: "8 Iron", loft: 38 },
      { name: "9 Iron", loft: 42 },
      { name: "PW", loft: 46 },
    ],
  },
  {
    brand: "Titleist",
    model: "T100S (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 19 },
      { name: "4 Iron", loft: 22 },
      { name: "5 Iron", loft: 25 },
      { name: "6 Iron", loft: 28 },
      { name: "7 Iron", loft: 32 },
      { name: "8 Iron", loft: 36 },
      { name: "9 Iron", loft: 40 },
      { name: "PW", loft: 44 },
    ],
  },
  {
    brand: "Titleist",
    model: "T150 (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 22 },
      { name: "5 Iron", loft: 25 },
      { name: "6 Iron", loft: 28 },
      { name: "7 Iron", loft: 31 },
      { name: "8 Iron", loft: 35 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 43 },
    ],
  },
  {
    brand: "Titleist",
    model: "T200 (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 24 },
      { name: "6 Iron", loft: 27 },
      { name: "7 Iron", loft: 30 },
      { name: "8 Iron", loft: 34 },
      { name: "9 Iron", loft: 38 },
      { name: "PW", loft: 43 },
    ],
  },
  {
    brand: "Titleist",
    model: "T350 (2024)",
    year: 2024,
    category: "Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28 },
      { name: "8 Iron", loft: 32 },
      { name: "9 Iron", loft: 37 },
      { name: "PW", loft: 42 },
      { name: "W", loft: 47 },
    ],
  },
  {
    brand: "Titleist",
    model: "AP1 (2016)",
    year: 2016,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29 },
      { name: "7 Iron", loft: 32 },
      { name: "8 Iron", loft: 36 },
      { name: "9 Iron", loft: 40 },
      { name: "PW", loft: 44 },
    ],
  },
  {
    brand: "Titleist",
    model: "AP3 (2018)",
    year: 2018,
    category: "Players Distance",
    clubs: [
      { name: "3 Iron", loft: 19 },
      { name: "4 Iron", loft: 22 },
      { name: "5 Iron", loft: 25 },
      { name: "6 Iron", loft: 28 },
      { name: "7 Iron", loft: 31 },
      { name: "8 Iron", loft: 35 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 43 },
      { name: "W", loft: 48 },
    ],
  },
  {
    brand: "Titleist",
    model: "Vokey SM10 Wedges",
    year: 2024,
    category: "Wedge Set",
    clubs: [
      { name: "46° Vokey PW", loft: 46 },
      { name: "48° Vokey GW", loft: 48 },
      { name: "50° Vokey AW", loft: 50 },
      { name: "52° Vokey GW", loft: 52 },
      { name: "54° Vokey SW", loft: 54 },
      { name: "56° Vokey SW", loft: 56 },
      { name: "58° Vokey LW", loft: 58 },
      { name: "60° Vokey LW", loft: 60 },
      { name: "62° Vokey LW", loft: 62 },
    ],
  },

  // ===========================
  // TAYLORMADE
  // ===========================
  {
    brand: "TaylorMade",
    model: "P770 (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "3 Iron", loft: 19 },
      { name: "4 Iron", loft: 21.5 },
      { name: "5 Iron", loft: 24.5 },
      { name: "6 Iron", loft: 28 },
      { name: "7 Iron", loft: 32 },
      { name: "8 Iron", loft: 36 },
      { name: "9 Iron", loft: 40.5 },
      { name: "PW", loft: 45 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P790 (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "3 Iron", loft: 19 },
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 23.5 },
      { name: "6 Iron", loft: 26.5 },
      { name: "7 Iron", loft: 30 },
      { name: "8 Iron", loft: 34.5 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 43.5 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P7MC (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 21 },
      { name: "4 Iron", loft: 24 },
      { name: "5 Iron", loft: 27 },
      { name: "6 Iron", loft: 31 },
      { name: "7 Iron", loft: 35 },
      { name: "8 Iron", loft: 39 },
      { name: "9 Iron", loft: 43 },
      { name: "PW", loft: 47 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P7MB (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 21 },
      { name: "4 Iron", loft: 24 },
      { name: "5 Iron", loft: 27 },
      { name: "6 Iron", loft: 31 },
      { name: "7 Iron", loft: 35 },
      { name: "8 Iron", loft: 39 },
      { name: "9 Iron", loft: 43 },
      { name: "PW", loft: 47 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Qi35 (2025)",
    year: 2025,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28.5 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 38 },
      { name: "PW", loft: 43 },
      { name: "AW", loft: 49 },
      { name: "SW", loft: 54 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Qi35 Max (2025)",
    year: 2025,
    category: "Super Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 24 },
      { name: "7 Iron", loft: 27 },
      { name: "8 Iron", loft: 31.5 },
      { name: "9 Iron", loft: 36 },
      { name: "PW", loft: 41 },
      { name: "AW", loft: 47 },
      { name: "SW", loft: 53 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Stealth 2 (2023)",
    year: 2023,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28.5 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 38 },
      { name: "PW", loft: 43 },
      { name: "AW", loft: 49 },
      { name: "SW", loft: 54 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "SIM2 Max (2021)",
    year: 2021,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28.5 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 38 },
      { name: "PW", loft: 43 },
      { name: "AW", loft: 49 },
      { name: "SW", loft: 54 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "MG4 Wedges",
    year: 2024,
    category: "Wedge Set",
    clubs: [
      { name: "46° MG4 PW", loft: 46 },
      { name: "48° MG4", loft: 48 },
      { name: "50° MG4", loft: 50 },
      { name: "52° MG4", loft: 52 },
      { name: "54° MG4 SW", loft: 54 },
      { name: "56° MG4 SW", loft: 56 },
      { name: "58° MG4 LW", loft: 58 },
      { name: "60° MG4 LW", loft: 60 },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Qi35 Hybrids & Fairways (2025)",
    year: 2025,
    category: "Hybrid/Fairway",
    clubs: [
      { name: "3 Wood", loft: 15 },
      { name: "5 Wood", loft: 19 },
      { name: "7 Wood", loft: 22 },
      { name: "3 Hybrid", loft: 19.5 },
      { name: "4 Hybrid", loft: 22 },
      { name: "5 Hybrid", loft: 25 },
      { name: "6 Hybrid", loft: 28 },
    ],
  },

  // ===========================
  // CALLAWAY
  // ===========================
  {
    brand: "Callaway",
    model: "Apex Pro (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20 },
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29 },
      { name: "7 Iron", loft: 33 },
      { name: "8 Iron", loft: 37 },
      { name: "9 Iron", loft: 41 },
      { name: "PW", loft: 45 },
    ],
  },
  {
    brand: "Callaway",
    model: "Apex (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 20 },
      { name: "5 Iron", loft: 23 },
      { name: "6 Iron", loft: 26 },
      { name: "7 Iron", loft: 29 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 37.5 },
      { name: "PW", loft: 42 },
      { name: "AW", loft: 47 },
    ],
  },
  {
    brand: "Callaway",
    model: "Paradym Ai Smoke (2024)",
    year: 2024,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 24.5 },
      { name: "7 Iron", loft: 27.5 },
      { name: "8 Iron", loft: 31.5 },
      { name: "9 Iron", loft: 36 },
      { name: "PW", loft: 41 },
      { name: "AW", loft: 46 },
      { name: "SW", loft: 51 },
    ],
  },
  {
    brand: "Callaway",
    model: "Paradym Ai Smoke Max (2024)",
    year: 2024,
    category: "Super Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 21 },
      { name: "6 Iron", loft: 23.5 },
      { name: "7 Iron", loft: 26.5 },
      { name: "8 Iron", loft: 30 },
      { name: "9 Iron", loft: 35 },
      { name: "PW", loft: 40 },
      { name: "AW", loft: 45 },
      { name: "SW", loft: 50 },
    ],
  },
  {
    brand: "Callaway",
    model: "Big Bertha (2023)",
    year: 2023,
    category: "Super Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28 },
      { name: "8 Iron", loft: 32 },
      { name: "9 Iron", loft: 37 },
      { name: "PW", loft: 42 },
      { name: "AW", loft: 47 },
      { name: "SW", loft: 52 },
    ],
  },
  {
    brand: "Callaway",
    model: "Mavrik (2020)",
    year: 2020,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 18 },
      { name: "5 Iron", loft: 21 },
      { name: "6 Iron", loft: 24 },
      { name: "7 Iron", loft: 27 },
      { name: "8 Iron", loft: 31.5 },
      { name: "9 Iron", loft: 36 },
      { name: "PW", loft: 41 },
      { name: "AW", loft: 46 },
      { name: "GW", loft: 51 },
      { name: "SW", loft: 56 },
    ],
  },
  {
    brand: "Callaway",
    model: "Jaws Raw Wedges",
    year: 2024,
    category: "Wedge Set",
    clubs: [
      { name: "46° Jaws PW", loft: 46 },
      { name: "48° Jaws", loft: 48 },
      { name: "50° Jaws AW", loft: 50 },
      { name: "52° Jaws GW", loft: 52 },
      { name: "54° Jaws SW", loft: 54 },
      { name: "56° Jaws SW", loft: 56 },
      { name: "58° Jaws LW", loft: 58 },
      { name: "60° Jaws LW", loft: 60 },
    ],
  },
  {
    brand: "Callaway",
    model: "Paradym Ai Smoke Hybrids & Fairways (2024)",
    year: 2024,
    category: "Hybrid/Fairway",
    clubs: [
      { name: "3 Wood", loft: 15 },
      { name: "5 Wood", loft: 18 },
      { name: "7 Wood", loft: 21 },
      { name: "2 Hybrid", loft: 17 },
      { name: "3 Hybrid", loft: 19 },
      { name: "4 Hybrid", loft: 22 },
      { name: "5 Hybrid", loft: 25 },
      { name: "6 Hybrid", loft: 28 },
    ],
  },

  // ===========================
  // PING
  // ===========================
  {
    brand: "Ping",
    model: "i230 (2023)",
    year: 2023,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20 },
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29.5 },
      { name: "7 Iron", loft: 33.5 },
      { name: "8 Iron", loft: 38 },
      { name: "9 Iron", loft: 42.5 },
      { name: "PW", loft: 47 },
      { name: "UW", loft: 52 },
    ],
  },
  {
    brand: "Ping",
    model: "i210 (2018)",
    year: 2018,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 19 },
      { name: "4 Iron", loft: 22.5 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29.5 },
      { name: "7 Iron", loft: 33 },
      { name: "8 Iron", loft: 37 },
      { name: "9 Iron", loft: 41 },
      { name: "PW", loft: 45 },
      { name: "UW", loft: 50 },
    ],
  },
  {
    brand: "Ping",
    model: "G430 (2023)",
    year: 2023,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 20.5 },
      { name: "5 Iron", loft: 23.5 },
      { name: "6 Iron", loft: 26.5 },
      { name: "7 Iron", loft: 30 },
      { name: "8 Iron", loft: 34.5 },
      { name: "9 Iron", loft: 39.5 },
      { name: "PW", loft: 44.5 },
      { name: "UW", loft: 49.5 },
      { name: "SW", loft: 54 },
    ],
  },
  {
    brand: "Ping",
    model: "G430 Max (2023)",
    year: 2023,
    category: "Super Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28.5 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 38.5 },
      { name: "PW", loft: 43.5 },
      { name: "UW", loft: 49 },
      { name: "SW", loft: 54 },
    ],
  },
  {
    brand: "Ping",
    model: "G425 (2021)",
    year: 2021,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 24 },
      { name: "6 Iron", loft: 27 },
      { name: "7 Iron", loft: 31 },
      { name: "8 Iron", loft: 35.5 },
      { name: "9 Iron", loft: 40.5 },
      { name: "PW", loft: 45.5 },
      { name: "UW", loft: 50 },
      { name: "SW", loft: 55 },
    ],
  },
  {
    brand: "Ping",
    model: "Zing (1990)",
    year: 1990,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20.5 },
      { name: "4 Iron", loft: 24 },
      { name: "5 Iron", loft: 27 },
      { name: "6 Iron", loft: 30.5 },
      { name: "7 Iron", loft: 34.5 },
      { name: "8 Iron", loft: 38.5 },
      { name: "9 Iron", loft: 42.5 },
      { name: "PW", loft: 47 },
      { name: "SW", loft: 52 },
    ],
  },
  {
    brand: "Ping",
    model: "G430 Hybrids & Fairways (2023)",
    year: 2023,
    category: "Hybrid/Fairway",
    clubs: [
      { name: "3 Wood", loft: 14.5 },
      { name: "5 Wood", loft: 17.5 },
      { name: "3 Hybrid", loft: 19 },
      { name: "4 Hybrid", loft: 22 },
      { name: "5 Hybrid", loft: 26 },
      { name: "6 Hybrid", loft: 30 },
    ],
  },
  {
    brand: "Ping",
    model: "Glide 4.0 Wedges",
    year: 2023,
    category: "Wedge Set",
    clubs: [
      { name: "46° Glide PW", loft: 46 },
      { name: "50° Glide GW", loft: 50 },
      { name: "52° Glide GW", loft: 52 },
      { name: "54° Glide SW", loft: 54 },
      { name: "56° Glide SW", loft: 56 },
      { name: "58° Glide LW", loft: 58 },
      { name: "60° Glide LW", loft: 60 },
    ],
  },

  // ===========================
  // COBRA
  // ===========================
  {
    brand: "Cobra",
    model: "Darkspeed (2024)",
    year: 2024,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 24.5 },
      { name: "7 Iron", loft: 27.5 },
      { name: "8 Iron", loft: 31.5 },
      { name: "9 Iron", loft: 36 },
      { name: "PW", loft: 41 },
      { name: "GW", loft: 46 },
      { name: "SW", loft: 51 },
    ],
  },
  {
    brand: "Cobra",
    model: "King Forged Tec (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 24 },
      { name: "6 Iron", loft: 27 },
      { name: "7 Iron", loft: 30.5 },
      { name: "8 Iron", loft: 35 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 44 },
    ],
  },
  {
    brand: "Cobra",
    model: "King Tour (2023)",
    year: 2023,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20 },
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29 },
      { name: "7 Iron", loft: 33 },
      { name: "8 Iron", loft: 37 },
      { name: "9 Iron", loft: 41 },
      { name: "PW", loft: 45 },
    ],
  },
  {
    brand: "Cobra",
    model: "Snakebite Wedges",
    year: 2024,
    category: "Wedge Set",
    clubs: [
      { name: "46° Snakebite PW", loft: 46 },
      { name: "50° Snakebite AW", loft: 50 },
      { name: "52° Snakebite GW", loft: 52 },
      { name: "54° Snakebite SW", loft: 54 },
      { name: "56° Snakebite SW", loft: 56 },
      { name: "58° Snakebite LW", loft: 58 },
      { name: "60° Snakebite LW", loft: 60 },
    ],
  },

  // ===========================
  // MIZUNO
  // ===========================
  {
    brand: "Mizuno",
    model: "Pro 243 (2024)",
    year: 2024,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20 },
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29.5 },
      { name: "7 Iron", loft: 33.5 },
      { name: "8 Iron", loft: 37.5 },
      { name: "9 Iron", loft: 42 },
      { name: "PW", loft: 46 },
    ],
  },
  {
    brand: "Mizuno",
    model: "Pro 245 (2024)",
    year: 2024,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 24 },
      { name: "6 Iron", loft: 27 },
      { name: "7 Iron", loft: 30.5 },
      { name: "8 Iron", loft: 34.5 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 43.5 },
    ],
  },
  {
    brand: "Mizuno",
    model: "Pro 225 (2022)",
    year: 2022,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 21 },
      { name: "5 Iron", loft: 24 },
      { name: "6 Iron", loft: 27 },
      { name: "7 Iron", loft: 30.5 },
      { name: "8 Iron", loft: 34.5 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 43.5 },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 925 Hot Metal (2024)",
    year: 2024,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 21.5 },
      { name: "6 Iron", loft: 24.5 },
      { name: "7 Iron", loft: 27.5 },
      { name: "8 Iron", loft: 32 },
      { name: "9 Iron", loft: 37 },
      { name: "PW", loft: 42 },
      { name: "GW", loft: 47 },
      { name: "SW", loft: 52 },
    ],
  },
  {
    brand: "Mizuno",
    model: "ES21 Wedges",
    year: 2021,
    category: "Wedge Set",
    clubs: [
      { name: "46° ES21 PW", loft: 46 },
      { name: "50° ES21 AW", loft: 50 },
      { name: "52° ES21 GW", loft: 52 },
      { name: "54° ES21 SW", loft: 54 },
      { name: "56° ES21 SW", loft: 56 },
      { name: "58° ES21 LW", loft: 58 },
      { name: "60° ES21 LW", loft: 60 },
    ],
  },

  // ===========================
  // SRIXON
  // ===========================
  {
    brand: "Srixon",
    model: "ZX5 Mk II (2023)",
    year: 2023,
    category: "Players Distance",
    clubs: [
      { name: "4 Iron", loft: 22 },
      { name: "5 Iron", loft: 25 },
      { name: "6 Iron", loft: 28 },
      { name: "7 Iron", loft: 31 },
      { name: "8 Iron", loft: 35 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 44 },
      { name: "AW", loft: 49 },
    ],
  },
  {
    brand: "Srixon",
    model: "ZX7 Mk II (2023)",
    year: 2023,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 20 },
      { name: "4 Iron", loft: 23 },
      { name: "5 Iron", loft: 26 },
      { name: "6 Iron", loft: 29 },
      { name: "7 Iron", loft: 33 },
      { name: "8 Iron", loft: 37 },
      { name: "9 Iron", loft: 41 },
      { name: "PW", loft: 46 },
    ],
  },
  {
    brand: "Srixon",
    model: "ZX4 Mk II (2023)",
    year: 2023,
    category: "Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28 },
      { name: "8 Iron", loft: 32 },
      { name: "9 Iron", loft: 37 },
      { name: "PW", loft: 42 },
      { name: "AW", loft: 47 },
      { name: "SW", loft: 52 },
    ],
  },
  {
    brand: "Srixon",
    model: "Z585 (2018)",
    year: 2018,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 20.5 },
      { name: "5 Iron", loft: 23.5 },
      { name: "6 Iron", loft: 26.5 },
      { name: "7 Iron", loft: 30 },
      { name: "8 Iron", loft: 34.5 },
      { name: "9 Iron", loft: 39.5 },
      { name: "PW", loft: 44.5 },
      { name: "AW", loft: 49.5 },
    ],
  },

  // ===========================
  // CLEVELAND
  // ===========================
  {
    brand: "Cleveland",
    model: "Launcher XL (2022)",
    year: 2022,
    category: "Super Game Improvement",
    clubs: [
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 28 },
      { name: "8 Iron", loft: 32 },
      { name: "9 Iron", loft: 36.5 },
      { name: "PW", loft: 41 },
      { name: "AW", loft: 46 },
      { name: "SW", loft: 51 },
    ],
  },
  {
    brand: "Cleveland",
    model: "Launcher HB Turbo (2020)",
    year: 2020,
    category: "Super Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 20 },
      { name: "5 Iron", loft: 23 },
      { name: "6 Iron", loft: 26 },
      { name: "7 Iron", loft: 29 },
      { name: "8 Iron", loft: 33 },
      { name: "9 Iron", loft: 38 },
      { name: "PW", loft: 43 },
      { name: "AW", loft: 48 },
      { name: "SW", loft: 53 },
    ],
  },
  {
    brand: "Cleveland",
    model: "RTX 6 ZipCore Wedges",
    year: 2023,
    category: "Wedge Set",
    clubs: [
      { name: "46° RTX6 PW", loft: 46 },
      { name: "50° RTX6 AW", loft: 50 },
      { name: "52° RTX6 GW", loft: 52 },
      { name: "54° RTX6 SW", loft: 54 },
      { name: "56° RTX6 SW", loft: 56 },
      { name: "58° RTX6 LW", loft: 58 },
      { name: "60° RTX6 LW", loft: 60 },
    ],
  },

  // ===========================
  // WILSON
  // ===========================
  {
    brand: "Wilson",
    model: "Staff Model (2023)",
    year: 2023,
    category: "Players",
    clubs: [
      { name: "3 Iron", loft: 21 },
      { name: "4 Iron", loft: 24 },
      { name: "5 Iron", loft: 27 },
      { name: "6 Iron", loft: 30 },
      { name: "7 Iron", loft: 34 },
      { name: "8 Iron", loft: 38 },
      { name: "9 Iron", loft: 42 },
      { name: "PW", loft: 46 },
    ],
  },
  {
    brand: "Wilson",
    model: "Dynapower (2023)",
    year: 2023,
    category: "Game Improvement",
    clubs: [
      { name: "4 Iron", loft: 19 },
      { name: "5 Iron", loft: 22 },
      { name: "6 Iron", loft: 25 },
      { name: "7 Iron", loft: 29 },
      { name: "8 Iron", loft: 34 },
      { name: "9 Iron", loft: 39 },
      { name: "PW", loft: 44 },
      { name: "AW", loft: 49 },
      { name: "SW", loft: 54 },
    ],
  },
];

// Get unique brands
export function getBrands(): string[] {
  return [...new Set(CLUB_CATALOG.map((c) => c.brand))].sort();
}

// Get models for a brand
export function getModelsForBrand(brand: string): ClubModel[] {
  return CLUB_CATALOG.filter((c) => c.brand === brand);
}

// Search catalog
export function searchCatalog(query: string): ClubModel[] {
  const q = query.toLowerCase();
  return CLUB_CATALOG.filter(
    (c) =>
      c.brand.toLowerCase().includes(q) ||
      c.model.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q)
  );
}
