export interface CatalogEntry {
  brand: string;
  model: string;
  year: number;
  variant?: string;
  clubs: {
    name: string;
    loft: number;
    type: "iron" | "wood" | "hybrid" | "wedge";
  }[];
}

export const clubCatalog: CatalogEntry[] = [
  // ============================================================
  // PING
  // ============================================================
  {
    brand: "Ping",
    model: "G430",
    year: 2023,
    clubs: [
      { name: "4i", loft: 20.5, type: "iron" },
      { name: "5i", loft: 23.5, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
      { name: "UW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G425",
    year: 2021,
    clubs: [
      { name: "4i", loft: 21.5, type: "iron" },
      { name: "5i", loft: 24.5, type: "iron" },
      { name: "6i", loft: 27.5, type: "iron" },
      { name: "7i", loft: 31, type: "iron" },
      { name: "8i", loft: 35, type: "iron" },
      { name: "9i", loft: 39.5, type: "iron" },
      { name: "PW", loft: 44.5, type: "wedge" },
      { name: "UW", loft: 50, type: "wedge" },
      { name: "SW", loft: 56, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G410",
    year: 2019,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 31.5, type: "iron" },
      { name: "8i", loft: 35.5, type: "iron" },
      { name: "9i", loft: 40, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
      { name: "UW", loft: 50, type: "wedge" },
      { name: "SW", loft: 56, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G400",
    year: 2017,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25.5, type: "iron" },
      { name: "6i", loft: 29, type: "iron" },
      { name: "7i", loft: 32.5, type: "iron" },
      { name: "8i", loft: 36.5, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 45.5, type: "wedge" },
      { name: "UW", loft: 50, type: "wedge" },
      { name: "SW", loft: 56, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G",
    year: 2016,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29.5, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41.5, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
      { name: "UW", loft: 51, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G30",
    year: 2014,
    clubs: [
      { name: "4i", loft: 22.5, type: "iron" },
      { name: "5i", loft: 26.5, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 33.5, type: "iron" },
      { name: "8i", loft: 37.5, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46.5, type: "wedge" },
      { name: "UW", loft: 51.5, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G25",
    year: 2013,
    clubs: [
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30.5, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42.5, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
      { name: "UW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G20",
    year: 2012,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26.5, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 33.5, type: "iron" },
      { name: "8i", loft: 37.5, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46.5, type: "wedge" },
      { name: "UW", loft: 51.5, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G15",
    year: 2010,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47.5, type: "wedge" },
      { name: "UW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "G10",
    year: 2008,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 28, type: "iron" },
      { name: "6i", loft: 32, type: "iron" },
      { name: "7i", loft: 36, type: "iron" },
      { name: "8i", loft: 40, type: "iron" },
      { name: "9i", loft: 44, type: "iron" },
      { name: "PW", loft: 48, type: "wedge" },
      { name: "UW", loft: 53, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "i230",
    year: 2023,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 22.5, type: "iron" },
      { name: "5i", loft: 25.5, type: "iron" },
      { name: "6i", loft: 29, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
      { name: "UW", loft: 50, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "i210",
    year: 2018,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29.5, type: "iron" },
      { name: "7i", loft: 33.5, type: "iron" },
      { name: "8i", loft: 37.5, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
      { name: "UW", loft: 51, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "i210",
    year: 2018,
    variant: "Power Spec",
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27.5, type: "iron" },
      { name: "7i", loft: 31, type: "iron" },
      { name: "8i", loft: 35.5, type: "iron" },
      { name: "9i", loft: 40, type: "iron" },
      { name: "PW", loft: 44.5, type: "wedge" },
      { name: "UW", loft: 49.5, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "i200",
    year: 2017,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
      { name: "UW", loft: 51, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "i500",
    year: 2019,
    clubs: [
      { name: "4i", loft: 20, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "Blueprint",
    year: 2020,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Ping",
    model: "S159 Wedges",
    year: 2023,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },

  // ============================================================
  // TITLEIST
  // ============================================================
  {
    brand: "Titleist",
    model: "T100",
    year: 2023,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "T150",
    year: 2023,
    clubs: [
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "T200",
    year: 2023,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "T300",
    year: 2023,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 36, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "W", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "T350",
    year: 2023,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 24.5, type: "iron" },
      { name: "7i", loft: 27.5, type: "iron" },
      { name: "8i", loft: 31.5, type: "iron" },
      { name: "9i", loft: 35.5, type: "iron" },
      { name: "PW", loft: 40.5, type: "wedge" },
      { name: "W", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "T400",
    year: 2023,
    clubs: [
      { name: "5i", loft: 21, type: "iron" },
      { name: "6i", loft: 24, type: "iron" },
      { name: "7i", loft: 27, type: "iron" },
      { name: "8i", loft: 30.5, type: "iron" },
      { name: "9i", loft: 34.5, type: "iron" },
      { name: "PW", loft: 39, type: "wedge" },
      { name: "W", loft: 44, type: "wedge" },
      { name: "W2", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "AP1 716",
    year: 2016,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30.5, type: "iron" },
      { name: "8i", loft: 34.5, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "W", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "AP2 716",
    year: 2016,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "AP1 714",
    year: 2014,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 31.5, type: "iron" },
      { name: "8i", loft: 35.5, type: "iron" },
      { name: "9i", loft: 39.5, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "W", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "AP2 714",
    year: 2014,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27.5, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 38.5, type: "iron" },
      { name: "9i", loft: 42.5, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "718 CB",
    year: 2018,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30.5, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "718 MB",
    year: 2018,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "718 AP1",
    year: 2018,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 23.5, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "W", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "718 AP2",
    year: 2018,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29.5, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "Vokey SM9",
    year: 2022,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "Vokey SM8",
    year: 2020,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },
  {
    brand: "Titleist",
    model: "Vokey SM7",
    year: 2017,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },

  // ============================================================
  // TAYLORMADE
  // ============================================================
  {
    brand: "TaylorMade",
    model: "P790 2023",
    year: 2023,
    clubs: [
      { name: "4i", loft: 19, type: "iron" },
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "AW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P790 2021",
    year: 2021,
    clubs: [
      { name: "4i", loft: 19, type: "iron" },
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25.5, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P790 2019",
    year: 2019,
    clubs: [
      { name: "4i", loft: 20.5, type: "iron" },
      { name: "5i", loft: 23.5, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P770",
    year: 2023,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 23.5, type: "iron" },
      { name: "5i", loft: 26.5, type: "iron" },
      { name: "6i", loft: 29.5, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P7MC",
    year: 2023,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 30.5, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "P7MB",
    year: 2023,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Stealth",
    year: 2022,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "AW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "SIM2 Max",
    year: 2021,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
      { name: "SW", loft: 53, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "SIM Max",
    year: 2020,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "M6",
    year: 2019,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "M4",
    year: 2018,
    clubs: [
      { name: "4i", loft: 19, type: "iron" },
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43.5, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "M2",
    year: 2017,
    clubs: [
      { name: "4i", loft: 19.5, type: "iron" },
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25.5, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33.5, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "RSi 1",
    year: 2015,
    clubs: [
      { name: "4i", loft: 20, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
      { name: "SW", loft: 54, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Burner 2.0",
    year: 2011,
    clubs: [
      { name: "3i", loft: 17, type: "iron" },
      { name: "4i", loft: 20, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38.5, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
      { name: "SW", loft: 53, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "Hi-Toe 3 Wedges",
    year: 2023,
    clubs: [
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },
  {
    brand: "TaylorMade",
    model: "MG4 Wedges",
    year: 2023,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },

  // ============================================================
  // CALLAWAY
  // ============================================================
  {
    brand: "Callaway",
    model: "Apex 2024",
    year: 2024,
    clubs: [
      { name: "4i", loft: 19.5, type: "iron" },
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "AW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Apex 2021",
    year: 2021,
    clubs: [
      { name: "4i", loft: 20.5, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29.5, type: "iron" },
      { name: "8i", loft: 33.5, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Apex 2019",
    year: 2019,
    clubs: [
      { name: "3i", loft: 18, type: "iron" },
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30.5, type: "iron" },
      { name: "8i", loft: 34.5, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Paradym",
    year: 2023,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "AW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Paradym X",
    year: 2023,
    clubs: [
      { name: "5i", loft: 21, type: "iron" },
      { name: "6i", loft: 24, type: "iron" },
      { name: "7i", loft: 27, type: "iron" },
      { name: "8i", loft: 31, type: "iron" },
      { name: "9i", loft: 36, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "AW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Rogue ST Max",
    year: 2022,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "AW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Mavrik",
    year: 2020,
    clubs: [
      { name: "4i", loft: 18, type: "iron" },
      { name: "5i", loft: 21, type: "iron" },
      { name: "6i", loft: 24, type: "iron" },
      { name: "7i", loft: 27, type: "iron" },
      { name: "8i", loft: 31, type: "iron" },
      { name: "9i", loft: 36, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "AW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Big Bertha",
    year: 2023,
    clubs: [
      { name: "5i", loft: 21, type: "iron" },
      { name: "6i", loft: 24, type: "iron" },
      { name: "7i", loft: 27, type: "iron" },
      { name: "8i", loft: 30.5, type: "iron" },
      { name: "9i", loft: 35, type: "iron" },
      { name: "PW", loft: 40, type: "wedge" },
      { name: "AW", loft: 45, type: "wedge" },
      { name: "SW", loft: 50, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Big Bertha B21",
    year: 2020,
    clubs: [
      { name: "5i", loft: 21, type: "iron" },
      { name: "6i", loft: 24, type: "iron" },
      { name: "7i", loft: 27, type: "iron" },
      { name: "8i", loft: 31, type: "iron" },
      { name: "9i", loft: 35.5, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "AW", loft: 46, type: "wedge" },
      { name: "SW", loft: 51, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "XR",
    year: 2016,
    clubs: [
      { name: "4i", loft: 20, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "X Forged",
    year: 2018,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Jaws Raw",
    year: 2022,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },
  {
    brand: "Callaway",
    model: "Jaws Full Toe",
    year: 2023,
    clubs: [
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },

  // ============================================================
  // COBRA
  // ============================================================
  {
    brand: "Cobra",
    model: "King Tour",
    year: 2022,
    clubs: [
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29.5, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41.5, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "King Forged Tec",
    year: 2022,
    clubs: [
      { name: "4i", loft: 19.5, type: "iron" },
      { name: "5i", loft: 22.5, type: "iron" },
      { name: "6i", loft: 25.5, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "LTDx",
    year: 2022,
    clubs: [
      { name: "5i", loft: 21.5, type: "iron" },
      { name: "6i", loft: 24.5, type: "iron" },
      { name: "7i", loft: 27.5, type: "iron" },
      { name: "8i", loft: 31.5, type: "iron" },
      { name: "9i", loft: 36, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "GW", loft: 46, type: "wedge" },
      { name: "SW", loft: 51, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "Radspeed",
    year: 2021,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "Speedzone",
    year: 2020,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "King F9",
    year: 2019,
    clubs: [
      { name: "5i", loft: 22.5, type: "iron" },
      { name: "6i", loft: 25.5, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 42.5, type: "wedge" },
      { name: "GW", loft: 47.5, type: "wedge" },
      { name: "SW", loft: 52.5, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "King F8",
    year: 2018,
    clubs: [
      { name: "5i", loft: 22.5, type: "iron" },
      { name: "6i", loft: 25.5, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "GW", loft: 48, type: "wedge" },
      { name: "SW", loft: 53, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "Fly-Z",
    year: 2015,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30.5, type: "iron" },
      { name: "8i", loft: 34.5, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "GW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Cobra",
    model: "King One Length",
    year: 2018,
    variant: "One Length",
    clubs: [
      { name: "5i", loft: 23.5, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 29.5, type: "iron" },
      { name: "8i", loft: 33.5, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "GW", loft: 48, type: "wedge" },
    ],
  },

  // ============================================================
  // MIZUNO
  // ============================================================
  {
    brand: "Mizuno",
    model: "JPX 925 Hot Metal",
    year: 2024,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 925 Hot Metal Pro",
    year: 2024,
    clubs: [
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "GW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 925 Forged",
    year: 2024,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 32, type: "iron" },
      { name: "8i", loft: 36, type: "iron" },
      { name: "9i", loft: 40, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 923 Hot Metal",
    year: 2023,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 923 Forged",
    year: 2023,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28.5, type: "iron" },
      { name: "7i", loft: 32, type: "iron" },
      { name: "8i", loft: 36, type: "iron" },
      { name: "9i", loft: 40.5, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 921 Hot Metal",
    year: 2021,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 42.5, type: "wedge" },
      { name: "GW", loft: 47.5, type: "wedge" },
      { name: "SW", loft: 52.5, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 921 Forged",
    year: 2021,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 29, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 45.5, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 919 Hot Metal",
    year: 2019,
    clubs: [
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "GW", loft: 48, type: "wedge" },
      { name: "SW", loft: 53, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "JPX 919 Forged",
    year: 2019,
    clubs: [
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "MP-20 MMC",
    year: 2020,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "MP-20 MB",
    year: 2020,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "MP-18 SC",
    year: 2018,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "MP-5",
    year: 2014,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 28, type: "iron" },
      { name: "6i", loft: 32, type: "iron" },
      { name: "7i", loft: 36, type: "iron" },
      { name: "8i", loft: 40, type: "iron" },
      { name: "9i", loft: 44, type: "iron" },
      { name: "PW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "T22 Wedges",
    year: 2022,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },
  {
    brand: "Mizuno",
    model: "T20 Wedges",
    year: 2020,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },

  // ============================================================
  // CLEVELAND
  // ============================================================
  {
    brand: "Cleveland",
    model: "Launcher XL2",
    year: 2023,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "DW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "Launcher XL",
    year: 2022,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28.5, type: "iron" },
      { name: "8i", loft: 32.5, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 42.5, type: "wedge" },
      { name: "DW", loft: 47.5, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "CBX",
    year: 2018,
    clubs: [
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30.5, type: "iron" },
      { name: "8i", loft: 34.5, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "GW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "RTX 6 ZipCore",
    year: 2023,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "64°", loft: 64, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "RTX 5",
    year: 2021,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "RTX 4",
    year: 2019,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },
  {
    brand: "Cleveland",
    model: "588 RTX 2.0",
    year: 2014,
    clubs: [
      { name: "46°", loft: 46, type: "wedge" },
      { name: "48°", loft: 48, type: "wedge" },
      { name: "50°", loft: 50, type: "wedge" },
      { name: "52°", loft: 52, type: "wedge" },
      { name: "54°", loft: 54, type: "wedge" },
      { name: "56°", loft: 56, type: "wedge" },
      { name: "58°", loft: 58, type: "wedge" },
      { name: "60°", loft: 60, type: "wedge" },
      { name: "62°", loft: 62, type: "wedge" },
    ],
  },

  // ============================================================
  // SRIXON
  // ============================================================
  {
    brand: "Srixon",
    model: "ZX5 Mk II",
    year: 2023,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 30.5, type: "iron" },
      { name: "8i", loft: 34.5, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Srixon",
    model: "ZX7 Mk II",
    year: 2023,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Srixon",
    model: "ZX5",
    year: 2021,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 31, type: "iron" },
      { name: "8i", loft: 35, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
      { name: "AW", loft: 49, type: "wedge" },
    ],
  },
  {
    brand: "Srixon",
    model: "ZX7",
    year: 2021,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Srixon",
    model: "Z 785",
    year: 2018,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Srixon",
    model: "Z 585",
    year: 2018,
    clubs: [
      { name: "4i", loft: 21, type: "iron" },
      { name: "5i", loft: 23.5, type: "iron" },
      { name: "6i", loft: 26.5, type: "iron" },
      { name: "7i", loft: 30, type: "iron" },
      { name: "8i", loft: 34, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
    ],
  },

  // ============================================================
  // WILSON
  // ============================================================
  {
    brand: "Wilson",
    model: "Staff Model CB",
    year: 2023,
    clubs: [
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 29, type: "iron" },
      { name: "7i", loft: 33, type: "iron" },
      { name: "8i", loft: 37, type: "iron" },
      { name: "9i", loft: 41, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Wilson",
    model: "Staff Model Blade",
    year: 2023,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Wilson",
    model: "Dynapower",
    year: 2023,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Wilson",
    model: "D9",
    year: 2021,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 37, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
    ],
  },
  {
    brand: "Wilson",
    model: "D7",
    year: 2019,
    clubs: [
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 42.5, type: "wedge" },
      { name: "GW", loft: 47.5, type: "wedge" },
    ],
  },

  // ============================================================
  // BRIDGESTONE
  // ============================================================
  {
    brand: "Bridgestone",
    model: "Tour B X",
    year: 2022,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 32, type: "iron" },
      { name: "8i", loft: 36, type: "iron" },
      { name: "9i", loft: 40, type: "iron" },
      { name: "PW", loft: 45, type: "wedge" },
    ],
  },
  {
    brand: "Bridgestone",
    model: "Tour B JGR",
    year: 2022,
    clubs: [
      { name: "5i", loft: 22, type: "iron" },
      { name: "6i", loft: 25, type: "iron" },
      { name: "7i", loft: 28, type: "iron" },
      { name: "8i", loft: 32, type: "iron" },
      { name: "9i", loft: 36, type: "iron" },
      { name: "PW", loft: 41, type: "wedge" },
      { name: "AW", loft: 46, type: "wedge" },
      { name: "SW", loft: 51, type: "wedge" },
    ],
  },

  // ============================================================
  // NIKE (historical)
  // ============================================================
  {
    brand: "Nike",
    model: "VR Pro Combo",
    year: 2011,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27.5, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 38.5, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Nike",
    model: "Slingshot",
    year: 2008,
    clubs: [
      { name: "4i", loft: 22, type: "iron" },
      { name: "5i", loft: 25, type: "iron" },
      { name: "6i", loft: 28, type: "iron" },
      { name: "7i", loft: 31, type: "iron" },
      { name: "8i", loft: 35, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "AW", loft: 48, type: "wedge" },
    ],
  },
  {
    brand: "Nike",
    model: "Victory Red",
    year: 2009,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },

  // ============================================================
  // ADAMS (historical)
  // ============================================================
  {
    brand: "Adams",
    model: "Idea a12OS",
    year: 2012,
    clubs: [
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 37.5, type: "iron" },
      { name: "PW", loft: 42, type: "wedge" },
      { name: "GW", loft: 47, type: "wedge" },
      { name: "SW", loft: 52, type: "wedge" },
    ],
  },
  {
    brand: "Adams",
    model: "XTD",
    year: 2014,
    clubs: [
      { name: "4i", loft: 20, type: "iron" },
      { name: "5i", loft: 23, type: "iron" },
      { name: "6i", loft: 26, type: "iron" },
      { name: "7i", loft: 29, type: "iron" },
      { name: "8i", loft: 33, type: "iron" },
      { name: "9i", loft: 38, type: "iron" },
      { name: "PW", loft: 43, type: "wedge" },
      { name: "GW", loft: 48, type: "wedge" },
    ],
  },

  // ============================================================
  // BEN HOGAN (historical)
  // ============================================================
  {
    brand: "Ben Hogan",
    model: "PTx PRO",
    year: 2020,
    clubs: [
      { name: "3i", loft: 20, type: "iron" },
      { name: "4i", loft: 23, type: "iron" },
      { name: "5i", loft: 26, type: "iron" },
      { name: "6i", loft: 30, type: "iron" },
      { name: "7i", loft: 34, type: "iron" },
      { name: "8i", loft: 38, type: "iron" },
      { name: "9i", loft: 42, type: "iron" },
      { name: "PW", loft: 46, type: "wedge" },
    ],
  },
  {
    brand: "Ben Hogan",
    model: "Edge EX",
    year: 2019,
    clubs: [
      { name: "5i", loft: 24, type: "iron" },
      { name: "6i", loft: 27, type: "iron" },
      { name: "7i", loft: 31, type: "iron" },
      { name: "8i", loft: 35, type: "iron" },
      { name: "9i", loft: 39, type: "iron" },
      { name: "PW", loft: 44, type: "wedge" },
    ],
  },
  {
    brand: "Ben Hogan",
    model: "Ft. Worth 15",
    year: 2015,
    clubs: [
      { name: "3i", loft: 21, type: "iron" },
      { name: "4i", loft: 24, type: "iron" },
      { name: "5i", loft: 27, type: "iron" },
      { name: "6i", loft: 31, type: "iron" },
      { name: "7i", loft: 35, type: "iron" },
      { name: "8i", loft: 39, type: "iron" },
      { name: "9i", loft: 43, type: "iron" },
      { name: "PW", loft: 47, type: "wedge" },
    ],
  },
];

// ============================================================
// Helper functions
// ============================================================

/**
 * Returns a sorted list of unique brand names in the catalog.
 */
export function getBrands(): string[] {
  const brands = new Set<string>();
  for (const entry of clubCatalog) {
    brands.add(entry.brand);
  }
  return Array.from(brands).sort();
}

/**
 * Returns all model/year/variant combinations for a given brand,
 * sorted by year descending.
 */
export function getModels(
  brand: string
): { model: string; year: number; variant?: string }[] {
  const results: { model: string; year: number; variant?: string }[] = [];
  for (const entry of clubCatalog) {
    if (entry.brand === brand) {
      const item: { model: string; year: number; variant?: string } = {
        model: entry.model,
        year: entry.year,
      };
      if (entry.variant) {
        item.variant = entry.variant;
      }
      results.push(item);
    }
  }
  return results.sort((a, b) => b.year - a.year);
}

/**
 * Finds and returns the catalog entry matching the given brand, model,
 * and optional variant. Returns undefined if no match is found.
 */
export function getClubsForModel(
  brand: string,
  model: string,
  variant?: string
): CatalogEntry | undefined {
  return clubCatalog.find(
    (entry) =>
      entry.brand === brand &&
      entry.model === model &&
      (variant === undefined
        ? entry.variant === undefined
        : entry.variant === variant)
  );
}
